@all:
	xcursorgen cursors/default.cursor cursors/default

install:
	rm -rf ~/.local/share/icons/Colleoni
	mkdir -p ~/.local/share/icons/Colleoni
	cp index.theme ~/.local/share/icons/Colleoni/index.theme
	cp -r cursors ~/.local/share/icons/Colleoni/cursors
