@all:
	xcursorgen cursors/default.cursor cursors/default

install:
	rm -rf ~/.local/share/icons/PD
	mkdir -p ~/.local/share/icons/PD
	cp index.theme ~/.local/share/icons/PD/index.theme
	cp -r cursors ~/.local/share/icons/PD/cursors
