@all:
	xcursorgen cursors/default.cursor cursors/default

install:
	rm -rf ~/.local/share/icons/E405
	mkdir -p ~/.local/share/icons/E405
	cp index.theme ~/.local/share/icons/E405/index.theme
	cp -r cursors ~/.local/share/icons/E405/cursors
