@all:
	xcursorgen cursors/default.cursor cursors/default

install:
	rm -rf ~/.local/share/icons/ETR521
	mkdir -p ~/.local/share/icons/ETR521
	cp index.theme ~/.local/share/icons/ETR521/index.theme
	cp -r cursors ~/.local/share/icons/ETR521/cursors
