@all:
	xcursorgen cursors/default.cursor cursors/default

install:
	rm -rf ~/.local/share/icons/ALN668
	mkdir -p ~/.local/share/icons/ALN668
	cp index.theme ~/.local/share/icons/ALN668/index.theme
	cp -r cursors ~/.local/share/icons/ALN668/cursors
