@all:
	xcursorgen cursors/default.cursor cursors/default

install:
	rm -rf ~/.local/share/icons/TSR
	mkdir -p ~/.local/share/icons/TSR
	cp index.theme ~/.local/share/icons/TSR/index.theme
	cp -r cursors ~/.local/share/icons/TSR/cursors
